name: src

on:
  push:
    paths:
      - 'src/**'
      - '**.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Install gcc
        run: |
          sudo apt-get install lib32ncurses5 lib32tinfo5 libc6-i386 -y
          wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/10-2020q4/gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.bz2
          tar -xf gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.bz2
          echo `pwd`/gcc-arm-none-eabi-10-2020-q4-major/bin >> $GITHUB_PATH

      - name: build template
        working-directory: template
        run: |
          make -C template

      - name: build src
        working-directory: src
        run: |
          make -C gcc

      - name: upload template
        uses: actions/upload-artifact@v2
        with:
          name: template_upload
          path: src/template/

      - name: upload src
        uses: actions/upload-artifact@v2
        with:
          name: gcc_upload
          path: src/gcc/
